### ISSUE TITLE
Invoke commands for Precious M+ posts

### ISSUE THREAD

**Issue by Tueri** [Icecrown-Community/Icecrown-Precious-Bot-Public#63]
As discussed recently, having a way to invoke the M+ bot listing without navigating away from Discord would be beneficial.
I think this can be achieved in a few ways, and I think the most popular would likely be by formatted post that can be copy-pasted, that is visual and informative with the use of emoji.

### **Method 1:**
Basic key setup with no specific requirements, gold paid on same faction as boosted, any keys, no note:
![image](https://user-images.githubusercontent.com/43845551/115249668-bef9cf00-a120-11eb-93f6-dee8ee7c2305.png)

Key setup where Tueri is specified as the tank to be pre-filled into the run, gold is paid on alliance for a horde boost, 2 keys specified where one is abbreviated and the other is typed in full, note included.
![image](https://user-images.githubusercontent.com/43845551/115250018-18fa9480-a121-11eb-9e17-22d7bb0633da.png)

_Alterations may need to be made to the keyholder option - "any key" should provoke the same result as the "Random Key" option from the form, so the keystone shows and gives prio as normal, but there may need to be a unique way to specify "different keys" and give each keyholder priority on the run, in each slot (I believe the bot will only give 2x keyholders prio currently) but only based on number of keys specified - 1x15 = 1x keyholder prio, 2x15 = 2x keyholder prio on different slots (but only where different keys are specified)._ 

Key setup with only requirement being that the keys are different:
![image](https://user-images.githubusercontent.com/43845551/115250351-6119b700-a121-11eb-97d3-e081e3e24c18.png)

Variations on:
- Horde Emoji - Tank, Healer, DPS1, DPS2 and "player tag".
- Gold Emoji - Amounts recognised in the same way as manual submits, no 'period' or 'comma' (eg. 437500).
- Keystone Emoji - Number prefix (1x, 4x, 6x etc) all keys abbreviated (The Necrotic Wake, NW, Necrotic), World Tour, Levelling, Custom (to allow for a wider variety of bot use).
- Note Emoji - No variation, note field as normal.
- /w line, no variation, should always be "/w name-realm".

Complex setup:
![image](https://user-images.githubusercontent.com/43845551/115253790-a095d280-a124-11eb-9db2-6d89a781baab.png)

Whether the items need to be separated by commas is down to technical constraints and I don't think it affects the user to put one between key/role values.

### **Method 2:**
Single line, worded string:
!post Horde, Tank @Tueri, 200k Blackmoore-a, 2x14 NW PF, Customer has NW Key, /w Tuerii-Kazzak
Invocation can also be used for method 1 if needs be, so everything invokes from !post (or similar), of course requires specific channels or returns error.

### **Method 3:**
Q&A type posting in a dedicated channel where Precious returns a question after command is invoked, basically the same as giveaway bot, but asking questions about the key:
![image](https://user-images.githubusercontent.com/43845551/115254670-7abcfd80-a125-11eb-95a1-5a9ad4056a2d.png)
Questions would be step-by-step and cover all grounds for the post, and would cycle the bot post into the channels as if using the forms as normal.

There would need to be clear information about how many roles can be placed into the bot before the post, we ofc don't want full groups being posted and spamming the channels, but I think 3x people missing a keyholder is a reasonable example of a use limit, so 3x fits in my mind.

There is nothing to say all 3 methods couldn't be used too, then advs can choose how they want to post, but it means keeping each updated with the others if so.

**Comment by Tueri** [comment]
From feedback I've had so far, Method 1 stands out from the rest!

**Comment by IndigoICC** [comment]
Will go a bit "inception-y" here and start with Method 3

/m3
I think this is will be slightly "clunky" - Say if it were Tuesday, and we had 10+ keys being created at the same time, there would be a lot of clutter. This could easily be combated by having multiple channels for each respective key type, but I much prefer Method 1/2 over this one.

/m2
Somewhat simple. I would think that it would be easily usable by advertisers. Personally, I don't like the formatting, though, and would prefer the display and input-style of Method 1, rather than having it one-lined. 

/m1
My favorite - Invoking via this particular format would be extremely efficient. 
(Kinda feel rather excited by looking at it).

// Would love to explore this further.

**Comment by DruidEmmaNielsen** [comment]
my 2 cents on why I would love Method 2) :) 

Since we already use submit commands, I feel like method 2 would be efficient, people can easily have a notepad++ open with everything pre-set and simple just change a name, or realm to quick copy paste runs 

if one has to set up 3x runs, or  client wants multiple keys, it would be easier to copy paste and do few changes, where all runs would then be lined up

ideas for the command could be something like the following

Have 2x channels for alliance/horde m+ posting
let's assume we are in #hordeposting 
!postm+ 15-t draenor-a 220k soa t-indigo-ragnaros h d d emmaicc-twistingnether

now to briefly explain each art.
!postm+   =   command to post
15-t  =  timed 15. 
Draenor-a = paid realm and faction
220k = pot
Soa = key

now comes the interesting part. 
t-indigo-ragnaros  = Tank Indigo-Ragnaros
h = free spot
d = free spot
d = free spot  
emmaicc-twistingnether =  Char to whisper for invite. 

this would immidiatly allow me to set up multiple runs beforehand

!postm+ 15-t draenor-a 220k dos t-indigo-ragnaros h d d emmaicc-twistingnether
!postm+ 15-t draenor-a 220k soa t-indigo-ragnaros h d d emmaicc-twistingnether
!postm+ 15-t draenor-a 220k hoa t-indigo-ragnaros h d d emmaicc-twistingnether

as an example, I really feel like people would quick get used to it, just like our submits.

**Comment by iElsha** [comment]
A different solution is being developed at the moment but the command choice might be used too in the future.

EDIT: I give more insight regarding this command.
The issue is the following, what can you do if a customer pay on a realm A faction A, realm B faction B, realm C faction B? This can not be handled.

**Comment by DruidEmmaNielsen** [comment]
> A different solution is being developed at the moment but the command choice might be used too in the future.
> 
> EDIT: I give more insight regarding this command.
> The issue is the following, what can you do if a customer pay on a realm A faction A, realm B faction B, realm C faction B? This can not be handled.

perhaps a formula kind of command? 

!postm+ 15-t gold draenor-a 120k, kazzak 100k, sylvanas-a 100k, key dos t-indigo-ragnaros h d d emmaicc-twistingnether

where "gold" is 1st part and "key" 2nd part and each gold-pay section is split by comma. Just like on excel/google sheets.

**Comment by iElsha** [comment]
This surely will come with a slash commands for more interaction

**Comment by ScroogeD2** [comment]
In case it's not a feature yet, it'd be nice to be able to specify which roles to ping. Similar to Dawn, where for example they can choose to ping the generic Tank/Healer/Dps roles (Rare and Epic roles would be our equivalents).
![image](https://user-images.githubusercontent.com/59540908/120904396-cafc0a80-c654-11eb-8b9f-a3bb30d9e806.png)

They can also choose to ping class roles or armor stack roles. This admittedly would be a niche feature, only useful in case of buyers who are looking for an item that multiple armor types but not all classes can loot, and I think that quite a few of these groups would be formed manually anyway. Thoughts?
![image](https://user-images.githubusercontent.com/59540908/120904424-ebc46000-c654-11eb-8b9b-f3cc3a1b5506.png)

**Comment by Efthymios-Papakostopoulos** [comment]
These are manual and not by a bot. We're using a bot here.

Also a new update coming soon :)

**Comment by iElsha** [comment]
With the new update is this still needed?

 If yes it will be done through slash command and be limited to a one realm-faction payment method and one dugeon.

**Comment by Tueri** [comment]
I think if we keep improving the webform then it's fine - the requests here can be implimented on the website; like specific class/armor pings, specific weapon-type/trinket/role-based pings etc, and the idea of keeping an alternative on discord is likely depreciated with our improvements.
