### ISSUE TITLE
Role reaction is removed when replacing a booster

### ISSUE THREAD

**Issue by ScroogeD2** [Icecrown-Community/Icecrown-Precious-Bot-Public#68]
After you open a run, click on one of the reactions to replace a booster and confirm it, the reaction is removed completely unless another booster reacted to it before the old booster got kicked out.
![image](https://user-images.githubusercontent.com/59540908/118341522-20e30400-b528-11eb-8a9e-28a362987b6c.png)

**Comment by Wanhedaa** [comment]
+1 bug, sometimes doesn't even post some roles originally (after posting, before closing). I had to manually replace 1-2 boosters, because the keyholder couldn't press on the keystone icon, because it was not there.

The boost was a +14 INTIME ToP.

**Comment by DruidEmmaNielsen** [comment]
Here some Tempoary Solution for people until hopefully it gets looked at.  Both Method works.

1.  Lock + Open run again (which means you spam current boosters)
2.  mention @name that the person needs to be replaced, and @epic healer ping so another healer reacts.  And then you can remove.

The reason this "bug" happens is because once you open a run, all reactions are cleared.  So when you react on healer to remove, bot removes your reaction + A reaction = which means all healer reactions gets cleared.

**Comment by iElsha** [comment]
That should be fixed with the new update, I keep it open in case
