### ISSUE TITLE
Demon hunter role skipped

### ISSUE THREAD

**Issue by Wanhedaa** [Icecrown-Community/Icecrown-Precious-Bot-Public#73]
I just got a new guy into the community, he claimed his roles, but the DH role got skipped. Not a big deal, but a "bug"
![image](https://user-images.githubusercontent.com/77633500/120118871-f5515200-c194-11eb-8e1b-603a05e59dde.png)

**Comment by iElsha** [comment]
DH role is not given when there is a demon hunter, but the character raider io is not skipped

**Comment by iElsha** [comment]
The behaviour is the same for DK.

The issue comes from the Discord role not being set up correctly.

It should have a space like" demon hunter" and not "demonhunter"

@Tueri this needs to be fixed, no issue on tech side for this. Close when you updated the role name everywhere in your embeds, then rename on discord ✅ . Please close the ticket when done

**Comment by Tueri** [comment]
Done
