### ISSUE TITLE
Feature: Sales gained from tickets nullified

### ISSUE THREAD

**Issue by Papa2324** [Icecrown-Community/Icecrown-Precious-Bot-Public#94]
@iElsha 😺

**Comment by iElsha** [comment]
After discussing with @Tueri we came up to the following solution.

## Introduction
- Where does the problem comes from?
Some advertisers are abusing the ticket tool by sniping customers.
- How to solve it?
Avoiding the sniping

## Do we nullify sales?
- Short answer: Nullifying the sales from ticket is not the solution to our problem.
- Long answer: The way we could nullify the sales are not good towards our advertisers. This will require them additional actions, more tracking that will not be appreciated from them. The way we could do it an user-friendly, without extra action/change of behavior does not exists. In any case, even if we add this change, we would never be 100% sure that the system is enforced (X advertiser submit Y run as a ticket, and not as out-of-ticket customer). This will most likely create some frictions, a bad environment therefore, this solution will most likely harm us more than it will do something good.

## What's the solution
We will establish a ticket queue manager where all advertisers currently eligible for tickets (legendary and elite only) claiming will be rotating (based on alphabetic order) to get the upcoming ticket on their turn.

#### How does it work?
You are eligible to get the upcoming ticket **if, and only if** you are available when getting called. What does it mean? When you are in second position, and the current first advertiser gets called, you must be **online/DND** status mode on Discord. Any advertiser **Idle/Offline** will be marked as not eligible and discarded (skipped).

#### How wIll you know your position in the queue?
- A channel displaying your position in the global rotation
- A DM from the bot when you become the upcoming advertiser (if eligible only, see above)


#### Why are we enforcing online/DND mode?
This is not correct toward the customer that we have on discord (ticket especially included) to not know that we are here to help him.

#### How can I claim a ticket?
You will be assigned by Precious in a ticket, when your turn has come. The ticket claim will be the same process as it is right now, clicking on the claim button.
*Subject to change, but the process will be made simple and not requiring extra actions from the advertiser*

#### I don't want to be part of the rotation this evening/today/this week/ever?
A blacklist role will be added where you will be auto-skipped. The role will be granted by reacting on a post. It will be removed by removing the reaction

#### Where will the system be used?
For now, we only plan to use it for PvE tickets as PvP is handled by a custom team

**Comment by Dejnaa** [comment]
Thank you, finally. Sounds like you did like some parts of my idea from February :D 
ETA?
